SOCNotificationIntranetPostInStreamTestIT
exoplatform/platform-qa-ui pull request #231
Opened 2018-11-07 12:35 UTC by balkissallem

2018-11-13 10:04 UTC, ilyeskallala commented
Reformat code with exo-formatter-settings http://developer.exoplatform.org/#id-formatter-settings

2018-11-13 10:05 UTC, ilyeskallala requested changes

2018-11-13 10:05 UTC, ilyeskallala commented on platform/src/test/java/org/exoplatform/platform/qa/ui/platform/social/functional/SOCNotificationIntranetPostInStreamTestIT.java
> +public class SOCNotificationIntranetPostInStreamTestIT extends Base {
Reformat code with exo-formatter-settings http://developer.exoplatform.org/#id-formatter-settings

2018-11-29 15:06 UTC, ilyeskallala approved these changes

2019-04-17 15:06 UTC, balkissallem commented on platform/src/test/java/org/exoplatform/platform/qa/ui/platform/social/functional/SOCNotificationIntranetPostInStreamTestIT.java
> +public class SOCNotificationIntranetPostInStreamTestIT extends Base {
done

2020-10-15 15:49 UTC, closed without merging